import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./components/layout/Layout";
import CreateMin from "./context/CreateMin";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bama Website - Next Router",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>
          <CreateMin>
            {children}
          </CreateMin>
        </Layout>
      </body>
    </html>
  );
}